# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: InfoPrima
email: infoprima@gmail.com

description: InfoPrima provides great services to solve Development business problems, brings capacity building for client's ICT infrastructure and knowledge, by using proper technology stack to achieve their goal. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mrpindo

phone: +62 - 838 7175 2782

# Postal address (add as many lines as necessary)
address:
  - line: Greater Jakarta, Indonesia

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


# Build settings
markdown: kramdown
permalink: pretty
